blog_app/urls.py
from django.urls import path

from . import views

app_name = 'blog_app'
urlpatterns = [
    path('', views.index, name='index'),
]

lexiconProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls')),
]
if settings.DEBUG:  # TODO: remove this in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
    path('special/', views.special, name='special'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit_profile/', views.edit_profile, name='edit_profile'),
]

blog_app/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    pub_date = models.DateTimeField("date published")
    content = models.TextField()

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.content[:100] + '...'
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfileInfo
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(),
        validators=[validate_password]
        )

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password)
        except ValidationError as e:
            self.add_error('password', e)
        return password


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

blog_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog_app/index.html')

users/views.py
from django.shortcuts import redirect, render
from users.forms import EditUserForm, UserForm, UserProfileInfoForm
from django.urls import reverse
from users.models import UserProfileInfo

from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

# Create your views here.
def index(request):
    return render(request, 'users/index.html')


def registerView(request):
    registered = False  # flag to check if user is registered
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            password = user_form.cleaned_data.get('password')

            try:
                validate_password(password) # validate password
            except ValidationError as e:
                user_form.add_error('password', e) # add error to form
                return render(request, 'users/register.html', {
                    'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered
                })
            
            # save user and profile
            user = user_form.save(commit=False)
            user.set_password(password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'users/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('users:index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password {password}")

            return HttpResponse("invalid login details supplied!")
        
    else:
        return render(request, 'users/login_logout.html', {})

@login_required
def logoutView(request):
    if request.method == 'POST':
        logout(request)
        return HttpResponseRedirect(reverse('users:index'))
    return render(request, 'users/login_logout.html', {})

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_profile(request):
    return render(request, 'users/profile.html')

@login_required
def edit_profile(request):
    user = request.user 
    profile = user.userprofileinfo

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)  
        profile_form = UserProfileInfoForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            print(request, 'Your profile has been updated successfully!')
            return redirect('edit_profile')
        else:
            print(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=user)
        profile_form = UserProfileInfoForm(instance=profile)

    return render(request, 'users/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

def edit_profile(request):
    user = request.user

    if user.is_superuser:
        # TODO Has no userprofileinfo object to edit 
        return redirect('admin:index')

    profile = user.userprofileinfo


    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=user)
        profile_form = UserProfileInfoForm(request.POST, request.FILES, instance=profile) 

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:profile')
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = EditUserForm(instance=user)
        profile_form = UserProfileInfoForm(instance=profile)

    return render(request, 'users/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}My Website{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body class="d-flex flex-column min-vh-100">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'users:index' %}">My Website</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:index' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        {% endif %}
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                    <span class="navbar-text px-3">
                        Welcome, <strong>{{ user.username }}</strong>!
                    </span>
                    <a class="btn " href="{% url 'users:logout' %}">Logout</a>
                    {% endif %}
                </div>
            </nav>
        </header>
        <main class="flex-fill">
            <div class="container">
                {% block content %}
                
                {% endblock %}
            </div>
        </main>
        <footer class="bg-light py-3 text-center">
            <p>&copy; 2024 My Website</p>
        </footer>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/blog_app/index.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

<h1>This is Blog index.html</h1>

{% block content %}

templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div>
    <h1>Edit Profile</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit" class="btn btn-primary">Save changes</button>
        
        <a href="{% url 'users:profile' %}">Cancel</a>
    </form>
</div>
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to the start page</h1>
    <p>This is the start page of the website.</p>
    <p>This site is a project build fron the django course at Lexicon</p>

    <h2>Labs</h2>
    <ul>
        <li>Forms</li>
        <li>Templates</li>
        <li>Static files</li>
        <li>Media files</li>
        <li>URLs</li>
        <li>Views</li>
        <li>Models</li>
        <li>Admin</li>
        <li>Blogs</li>
        <li>Users</li>
        <li>Login</li>
        <li>Logout</li>
        <li>Register</li>
    </ul>
{% endblock %}

templates/users/login_logout.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <h1 class="text-center py-4">{% if user.is_authenticated %}Logout{% else %}Login{% endif %}</h1>
    
    {% if user.is_authenticated %}
    <p>Are you sure you want to logout?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    {% else %}
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username" placeholder="Enter username" required>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" placeholder="Enter password" required>
            <input type="submit" value="Login">
        </form>
        <p class="text-center py-4">Don't have an account? <a href="{% url 'users:register' %}">Register here</a>.</p>


    {% endif %}
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}

<div>
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                {% if user.userprofileinfo.profile_pic %}
                <img src="{{ user.userprofileinfo.profile_pic.url }}" alt="Profile picture" style="max-width: 200px;">
                {% else %}
                <p>No profile picture uploaded.</p>
                {% endif %}

                <p>Profile site: {{ user.userprofileinfo.portfolio_site }}</p>
                <p>Username: {{ user.username }}</p>
                <p>Email: {{ user.email }}</p>
                <p>First name: {{ user.first_name }}</p>
                <p>Last name: {{ user.last_name }}</p>
                <p>Joined: {{ user.date_joined }}</p>

                <a href="{% url 'users:edit_profile' %}" class="btn btn-primary">Edit profile</a>
        </div>
    </div>
</div>




</div>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    {% if registered %}
    <div class="alert alert-success text-center">
        <p>You have successfully registered! You can now <a href="{% url 'users:login' %}">log in</a>.</p>
    </div>
    {% else %}
    <h1 class="text-center">Register</h1>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        <!-- Loop through form fields -->
        {% for field in user_form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
            <small class="helptext">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        {% endfor %}

        <!-- Profile form fields -->
        {% for field in profile_form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
            <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        {% endfor %}

        <button type="submit" class="btn">Register</button>
    </form>
    {% endif %}
</div>
{% endblock %}